if(EXISTS "/home/lupralo31/Escritorio/ROBOCUP_PRIVADO_CLON/robocupprivado/tests/runTests[1]_tests.cmake")
  include("/home/lupralo31/Escritorio/ROBOCUP_PRIVADO_CLON/robocupprivado/tests/runTests[1]_tests.cmake")
else()
  add_test(runTests_NOT_BUILT runTests_NOT_BUILT)
endif()
